# This is a basic workflow that is manually triggered

name: Artifact Storing Workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run script:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Executes python script that generates log file
    - name: Execute Logging Script
      run: python3 logfile_test.py

    - name: Archive Log Files as Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-file
        path: log_archive/test_file.py
