# This is a basic workflow that is manually triggered

name: Artifact Storing Workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-script:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Executes python script that generates log file
    - name: Prepare log_archive folder
      run: mkdir log_archive

    - name: Execute Logging Script
      run: python3 logfile_test.py

    - name: Create Artifact Folder
      run: mkdir -p ${{ github.workspace }}/Artifacts

    - name: Copy Log Archive folder
      run: cp -r 'log_archive/' '${{ github.workspace }}/Artifacts/log_archive'

    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/Artifacts
        name: ${{ github.run_number }}
