name: Remote Commands via SSH

on: workflow_dispatch

jobs:

  build:
    name: Execute-Command
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: python ~/Projects/SpaceLab/log_workflows/logfile_test.py
